corpus:    
    train_dataset: /mnt/fastd/patents/corpus_files_sample/train/
    test_dataset: /mnt/fastd/patents/corpus_files_sample/valid/
    max_seq_len: 20
    min_seq_len: 3   
    max_word_len: 50
    token_len: 25    
    train_corpus_lines: 60847050
    test_corpus_lines: 27914807    
    vocab_path: /mnt/fastd/patents/model/wp_vocab_hybrid_freq10k_75k.json
context:
    context_flag: true    
    context_path: /mnt/fastd/patents/model/context_vb_fixed.pck
model:
    hidden: 256
    context_embedding_size: 128
    layers: 8
    attn_heads: 8
train:
    batch_size: 256
    epochs: 10
    num_workers: 1
    with_cuda: true
    cuda_devices: null
    learning_rate: 0.001
    adam_weight_decay: 0.01
    adam_beta1: 0.9
    adam_beta2: 0.999    
    output_path: /mnt/fastd/patents/model/model
    log_path: /mnt/fastd/patents/model/log
    log_freq: 10